name: datazone-landingzone
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
  TF_DIRECTORY: ""
  
jobs:
  parse-datazone:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: get-datazone-yaml
        id: datazone-config
        run: |
          cd config
          ls *.yaml | jq -R . | jq -s .
          echo "datazone_config="$(ls *.yaml | jq -R . | jq -s .)"" >> $GITHUB_OUTPUT
    outputs: 
        datazone_config: ${{ steps.datazone-config.outputs.datazone_config }}
  
  datazone-domain:
    needs: [parse-datazone]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix: 
        domain: ${{fromJson(needs.parse-datazone.outputs.datazone_config)}}
    steps:
      - name: datazone-tf
        uses: actions/checkout@v4
        with:
          repository: hashi-demo-lab/template-datazone-domain
      - name: checkout-config
        uses: actions/checkout@v4
        with:
          repository: hashi-demo-lab/landingzone-datazone
          sparse-checkout: |
            config
      - name: check-directory
        id: check-dir
        run: |
          ls -l
          cd config
          ls -l 
