name: datazone-landingzone
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
  TF_DIRECTORY: ""
  
jobs:
  parse-datazone:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: get-datazone-yaml
        id: datazone-config
        run: |
          cd config
          ls -d */ | sed 's|/$||' | jq -R . | jq -s .
          echo "datazone_config="$(ls *.yaml | jq -R . | jq -s .)"" >> $GITHUB_OUTPUT
    outputs: 
        datazone_config: ${{ steps.datazone-config.outputs.datazone_config }}
